name: MIEWeb LaunchPad
description: Manage Containers via API
author: mieweb
branding:
  icon: "package"
  color: "purple"

inputs:
  api_key:
    description: "API Key for authentication"
    required: true
  api_url:
    description: "Base URL for the Container API"
    required: true
  template_name:
    description: "Container template (e.g., ghcr.io/mieweb/timeharbor:latest)"
    required: false
  container_env_vars:
    description: "Environment variables to set inside the container (JSON string)"
    required: false
  services:
    description: "Services configuration (JSON array)"
    required: false
  site_id:
    description: "Site ID for the container management system"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Check if action should run
      shell: bash
      id: should-run
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_CREATED: ${{ github.event.created }}
      run: |
        if [[ "$GITHUB_EVENT_NAME" != "push" ]] || [[ "$GITHUB_EVENT_CREATED" == "false" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
          echo "Skipping action: Push event with created=true"
        fi

    - name: Determine Target Branch Name
      shell: bash
      id: branch-name
      if: steps.should-run.outputs.should_run == 'true'
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "delete" ]]; then
          TARGET_BRANCH="$GITHUB_EVENT_REF"
          echo "Using deleted branch name: $TARGET_BRANCH"
        else
          TARGET_BRANCH="$GITHUB_REF_NAME"
          echo "Using current branch name: $TARGET_BRANCH"
        fi
        echo "target_branch=$TARGET_BRANCH" >> $GITHUB_OUTPUT

    # ── Phase 1: Create or locate the container ──
    - name: Create or Locate Container
      id: manage-container
      shell: bash
      if: ${{ (github.event_name == 'create' || github.event_name == 'push') && steps.should-run.outputs.should_run == 'true' }}
      env:
        API_URL: ${{ inputs.api_url }}
        API_KEY: ${{ inputs.api_key }}
        TEMPLATE_NAME: ${{ inputs.template_name }}
        SITE_ID: ${{ inputs.site_id }}
        SERVICES: ${{ inputs.services }}
        CONTAINER_ENV_VARS: ${{ inputs.container_env_vars }}
        GITHUB_REPOSITORY_FULL: ${{ github.repository }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        TARGET_BRANCH: ${{ steps.branch-name.outputs.target_branch }}
      run: |
        # 1. Generate Container Name
        REPO_NAME=$(basename "$GITHUB_REPOSITORY_FULL")
        CONTAINER_NAME="${GITHUB_REPOSITORY_OWNER}-${REPO_NAME}-${TARGET_BRANCH}"
        CONTAINER_NAME=${CONTAINER_NAME,,}
        CONTAINER_NAME=$(echo "$CONTAINER_NAME" | sed 's/[^a-z0-9-]/-/g')

        echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT
        echo "Managing Container: $CONTAINER_NAME"

        # 2. Check for existing container
        echo "Querying API: $API_URL/sites/$SITE_ID/containers?hostname=$CONTAINER_NAME"

        EXISTING_CONTAINER=$(curl -s -H "Authorization: Bearer $API_KEY" -H "Accept: application/json" \
          "$API_URL/sites/$SITE_ID/containers?hostname=$CONTAINER_NAME")

        echo "--- RAW API RESPONSE ---"
        echo "$EXISTING_CONTAINER"
        echo "------------------------"

        CONTAINER_ID=$(echo "$EXISTING_CONTAINER" | jq -r '.containers[0].id // empty')

        if [ -n "$CONTAINER_ID" ] && [ "$CONTAINER_ID" != "null" ]; then
          echo "Container already exists (ID: $CONTAINER_ID). Skipping creation."
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT
          echo "container_ready=true" >> $GITHUB_OUTPUT
        else
          echo "Container does not exist. Creating..."

          CREATE_PAYLOAD=$(jq -n \
            --arg hostname "$CONTAINER_NAME" \
            --arg template "$TEMPLATE_NAME" \
            --arg services "$SERVICES" \
            --arg env_vars "$CONTAINER_ENV_VARS" \
            '{
              hostname: $hostname,
              template: $template,
              services: ($services | fromjson? // []),
              environment: ($env_vars | fromjson? // {})
            }')

          echo "--- Create Payload ---"
          echo "$CREATE_PAYLOAD"
          echo "----------------------"

          CREATE_RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X POST "$API_URL/sites/$SITE_ID/containers" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "$CREATE_PAYLOAD")

          CREATE_BODY=$(echo "$CREATE_RESPONSE" | sed '$d')
          CREATE_CODE=$(echo "$CREATE_RESPONSE" | tail -1)

          if [ "$CREATE_CODE" -ge 200 ] && [ "$CREATE_CODE" -lt 300 ]; then
            NEW_ID=$(echo "$CREATE_BODY" | jq -r '.container.id // .id // empty')
            JOB_ID=$(echo "$CREATE_BODY" | jq -r '.jobId // empty')
            echo "Container created successfully (ID: $NEW_ID, Job ID: $JOB_ID)."
            echo "container_id=$NEW_ID" >> $GITHUB_OUTPUT
            echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
            echo "container_created=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Failed to create container. HTTP: $CREATE_CODE"
            echo "    Response: $CREATE_BODY"
            echo "FAILED=1" >> $GITHUB_ENV
            exit 1
          fi
        fi

    # ── Phase 2: Wait for the container to be running ──
    - name: Wait for Container to be Running
      id: wait-container
      shell: bash
      if: ${{ steps.manage-container.outputs.container_created == 'true' && env.FAILED != '1' }}
      env:
        API_URL: ${{ inputs.api_url }}
        API_KEY: ${{ inputs.api_key }}
        JOB_ID: ${{ steps.manage-container.outputs.job_id }}
        CONTAINER_NAME: ${{ steps.manage-container.outputs.container_name }}
      run: |
        MAX_ATTEMPTS=30       # Total wait: up to ~5 minutes (30 × 10s)
        POLL_INTERVAL=10      # Seconds between checks
        ATTEMPT=0

        echo "Waiting for job $JOB_ID (container '$CONTAINER_NAME') to complete..."

        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          ATTEMPT=$((ATTEMPT + 1))

          # Capture both body and HTTP status code
          RAW_RESPONSE=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Accept: application/json" \
            "$API_URL/jobs/$JOB_ID")

          HTTP_CODE=$(echo "$RAW_RESPONSE" | tail -1)
          RESPONSE_BODY=$(echo "$RAW_RESPONSE" | sed '$d')

          echo "  Attempt $ATTEMPT/$MAX_ATTEMPTS — HTTP $HTTP_CODE"

          # If we got a non-2xx response, retry
          if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
            echo "    API returned HTTP $HTTP_CODE"
            echo "    Response: $RESPONSE_BODY"
            sleep $POLL_INTERVAL
            continue
          fi

          # Validate the response is valid JSON before parsing
          if ! echo "$RESPONSE_BODY" | jq empty 2>/dev/null; then
            echo "    Response is not valid JSON — retrying."
            sleep $POLL_INTERVAL
            continue
          fi

          JOB_STATUS=$(echo "$RESPONSE_BODY" | jq -r '.status // "unknown"')
          CONTAINER_STATUS=$(echo "$RESPONSE_BODY" | jq -r '.container.status // "unknown"')
          echo "    Job: $JOB_STATUS | Container: $CONTAINER_STATUS"

          if [ "$JOB_STATUS" == "completed" ] || [ "$JOB_STATUS" == "success" ]; then
            if [ "$CONTAINER_STATUS" == "running" ]; then
              echo "Job completed and container is running!"
              echo "Waiting 10s for container to fully stabilize..."
              sleep 10
              echo "container_ready=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "::error::Job completed but container status is '$CONTAINER_STATUS'."
              echo "    Full response: $RESPONSE_BODY"
              echo "FAILED=1" >> $GITHUB_ENV
              exit 1
            fi
          fi

          if [ "$JOB_STATUS" == "failed" ] || [ "$JOB_STATUS" == "error" ]; then
            echo "::error::Job entered '$JOB_STATUS' state."
            echo "    Full response: $RESPONSE_BODY"
            echo "FAILED=1" >> $GITHUB_ENV
            exit 1
          fi

          # Job is still pending or running — keep polling
          sleep $POLL_INTERVAL
        done

        echo "::error::Timed out waiting for job to complete after $((MAX_ATTEMPTS * POLL_INTERVAL))s."
        echo "FAILED=1" >> $GITHUB_ENV
        exit 1

    # ── Container Deletion on Branch Deletion ──
    - name: Container Deletion on Branch Deletion
      shell: bash
      if: ${{ github.event_name == 'delete' && steps.should-run.outputs.should_run == 'true' }}
      env:
        GITHUB_REPOSITORY_FULL: ${{ github.repository }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        TARGET_BRANCH: ${{ steps.branch-name.outputs.target_branch }}
        API_KEY: ${{ inputs.api_key }}
        API_URL: ${{ inputs.api_url }}
        SITE_ID: ${{ inputs.site_id }}
      run: |
        REPO_NAME=$(basename "$GITHUB_REPOSITORY_FULL")
        CONTAINER_NAME="${GITHUB_REPOSITORY_OWNER}-${REPO_NAME}-${TARGET_BRANCH}"
        CONTAINER_NAME=${CONTAINER_NAME,,}
        CONTAINER_NAME=$(echo "$CONTAINER_NAME" | sed 's/[^a-z0-9-]/-/g')

        # Query /containers endpoint to get container.id using API Key authentication
        CONTAINERS_RESPONSE=$(curl -s -H "Authorization: Bearer $API_KEY" -H "Accept: application/json" "$API_URL/sites/$SITE_ID/containers?hostname=$CONTAINER_NAME")
        CONTAINER_ID=$(echo "$CONTAINERS_RESPONSE" | jq -r '.containers[0].id // empty')

        # DELETE /containers/:id
        if [ -n "$CONTAINER_ID" ] && [ "$CONTAINER_ID" != "null" ]; then
          DELETE_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $API_KEY" -X DELETE "$API_URL/sites/$SITE_ID/containers/$CONTAINER_ID")
          if [ "$DELETE_CODE" -eq 200 ] || [ "$DELETE_CODE" -eq 204 ]; then
             echo "Container $CONTAINER_NAME (ID: $CONTAINER_ID) has been deleted"
          else
             echo "::warning::Failed to delete container. HTTP: $DELETE_CODE"
          fi
        else
          echo "No container found to delete"
        fi

    - name: Catch All Failure Step
      if: env.FAILED == '1'
      shell: bash
      run: |
        echo "Workflow failed. See previous steps for details."
        exit 1
